chore(ci): update CI/CD
fix(ci): lint files in ci

chore(ci): add no-auto-update label

chore(ci): compile test files before e2e tests

chore(ci): configure percy for e2e tests

chore(ci): add percy webhook to ci

fix(ci): add netlify percy test path to config

chore(ci): fix github actions workflows

feat(ci): run lighthouse tests on github's runners

fix(ci): disable csp-xss test in lighthouse

chore(ci): rename netlify plugin

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -27,10 +27,6 @@ env:
   FORCE_COLOR: true
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-  # For use in the webdriver script (wdio.conf.js)
-  BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
-  BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
-
   # https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
   ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
 
@@ -44,6 +40,38 @@ jobs:
   #   steps:
   #     - name: Debugging context variables
   #       run: echo "$GITHUB_CONTEXT"
+
+  test:
+    name: Run test suite (Web Test Runner)
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      # Configures the node version used on GitHub-hosted runners
+      - name: Configure node version
+        uses: actions/setup-node@v2
+        with:
+          node-version: '16'
+          cache: npm
+
+      - name: Install dependencies
+        run: npm ci --prefer-offline
+
+      - name: Lint
+        run: npm run lint
+        continue-on-error: true
+
+      - name: Run tests
+        run: npm test
+
+      - name: JUnit Report Action
+        uses: mikepenz/action-junit-report@v2.8.2
+        if: always() # run always, even if tests fail, so we get reports in github UI
+        with:
+          report_paths: test-results/test-results.xml
+          fail_on_failure: true # fail the actions run if the tests failed
+
   build:
     name: Compile project
     outputs:
@@ -55,25 +83,20 @@ jobs:
           - '16'
           - '17'
     if: |
-      (
-        github.event_name == 'pull_request' &&
-        github.event.action == 'labeled' &&
-        (
-          github.event.label.name == 'run e2e' ||
-          github.event.label.name == 'ready to merge'
-        )
-      ) ||
-      (
-        github.event_name == 'pull_request' &&
-        github.event.action != 'labeled' &&
-        github.event.pull_request.draft == false &&
-        !contains(github.event.pull_request.labels.*.name, 'blocked') &&
-        !contains(github.event.pull_request.labels.*.name, 'skip ci') &&
-        !contains(github.event.pull_request.labels.*.name, 'work in progress') &&
-        !contains(github.event.pull_request.labels.*.name, 'on hold')
-      ) ||
-      github.event_name == 'workflow_dispatch' ||
-      github.event_name == 'push'
+      github.event_name == 'workflow_dispatch'
+      ||   github.event_name == 'push'
+      || ( github.event_name == 'pull_request'
+        && github.event.action == 'labeled'
+        && github.event.label.name == 'ready to merge'
+      )
+      || ( github.event_name == 'pull_request'
+        && github.event.action != 'labeled'
+        && github.event.pull_request.draft == false
+        && !contains(github.event.pull_request.labels.*.name, 'blocked')
+        && !contains(github.event.pull_request.labels.*.name, 'skip ci')
+        && !contains(github.event.pull_request.labels.*.name, 'work in progress')
+        && !contains(github.event.pull_request.labels.*.name, 'on hold')
+      )
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
@@ -94,111 +117,19 @@ jobs:
 
       - name: Build
         id: build
-        run: npm run build
+        run: |
+          npm run build
 
       # Upload compiled assets to make them available for downstream jobs
       - name: Upload artifacts
         uses: actions/upload-artifact@v2
         with:
           name: compiled-assets
-          path: ./{elements,core}/*/dist/*
           if-no-files-found: error
-
-  # Test command can run concurrent with e2e so it downloads the
-  # compiled assets from the build and uses those instead of reinstalling.
-  test:
-    name: Run test suite (Web Test Runner)
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
-
-      # Configures the node version used on GitHub-hosted runners
-      - name: Configure node version
-        uses: actions/setup-node@v2
-        with:
-          node-version: '16'
-          cache: npm
-
-      - name: Install dependencies
-        run: npm ci --prefer-offline
-
-      - name: Run tests
-        run: npm test
-
-  # E2E command can run concurrent with test so it downloads the
-  # compiled assets from the build and uses those instead of reinstalling.
-  # Only run visual tests if the PR is labeled "ready to merge" or "run e2e"
-  e2e:
-    name: Visual regression testing
-    needs: build
-    if: |
-      needs.build.result == 'success' &&
-      (
-        contains(github.event.pull_request.labels.*.name, 'ready to merge') ||
-        contains(github.event.pull_request.labels.*.name, 'run e2e') ||
-        contains(github.event.pull_request.user.login, 'dependabot')
-      ) &&
-      !contains(github.event.pull_request.labels.*.name, 'skip vrt')
-    runs-on: ubuntu-latest
-    steps:
-      - name: BrowserStack environment setup
-        uses: "browserstack/github-actions/setup-env@master"
-        with:
-          username: ${{ secrets.BROWSERSTACK_USER }}
-          access-key: ${{ secrets.BROWSERSTACK_KEY }}
-
-      - name: Start BrowserStackLocal
-        uses: browserstack/github-actions/setup-local@master
-        with:
-          local-testing: start
-          local-identifier: random
-          # local-logging-level: all-logs
-
-      - name: Checkout repository
-        uses: actions/checkout@v2
-
-      # Configures the node version used on GitHub-hosted runners
-      - name: Configure node version
-        uses: actions/setup-node@v2
-        with:
-          node-version: '16'
-          cache: npm
-
-      - name: Install dependencies
-        run: npm ci --prefer-offline
-
-      - name: Access compiled assets
-        uses: actions/download-artifact@v2
-        id: download-compiled-assets
-        with:
-          name: compiled-assets
-          path: .
-
-      - name: Build
-        if: failure()
-        run: npm run build
-
-      - name: Visual regression tests
-        run: npm run e2e -- --verbose
-
-      # Upload assets even if the e2e fails
-      - name: Archive baseline images
-        if: always()
-        uses: actions/upload-artifact@v2
-        with:
-          name: visual-regression-snapshots
           path: |
-            .tmp/
-            test/vrt-baseline
-            test/vrt-snapshots
-          if-no-files-found: error
-
-      - name: Stop BrowserStackLocal
-        if: always()
-        uses: browserstack/github-actions/setup-local@master
-        with:
-          local-testing: stop
+            core/
+            elements/
+            tools/
 
   # Validate the build to master was successful; open an issue if not
   validate:
@@ -206,7 +137,6 @@ jobs:
     needs:
       - build
       - test
-      - e2e
     if: always()
     runs-on: ubuntu-latest
     steps:
@@ -218,18 +148,16 @@ jobs:
           echo 'EOF' >> $GITHUB_ENV
       - name: Add a label if tests have passed (PR)
         if: |
-          github.event_name == 'pull_request' &&
-          needs.test.outcome != 'failure' &&
-          needs.e2e.outcome != 'failure'
+          github.event_name == 'pull_request'
+          && needs.test.outcome != 'failure'
         uses: actions-ecosystem/action-add-labels@v1
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           labels: AT passed
       - name: Add a label if tests have passed (dispatch)
         if: |
-          github.event_name == 'workflow_dispatch' &&
-          needs.test.outcome != 'failure' &&
-          needs.e2e.outcome != 'failure'
+          github.event_name == 'workflow_dispatch'
+          && needs.test.outcome != 'failure'
         uses: actions-ecosystem/action-add-labels@v1
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
@@ -237,17 +165,16 @@ jobs:
           number: ${{ env.prnumber }}
       - name: Remove the label if tests failed
         if: |
-          github.event_name == 'pull_request' &&
-          needs.test.outcome == 'failure' ||
-          needs.e2e.outcome == 'failure'
+          github.event_name == 'pull_request'
+          && needs.test.outcome == 'failure'
         uses: actions-ecosystem/action-remove-labels@v1
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           labels: AT passed
       - name: Open issue if build breaks
         if: |
-          needs.build.outcome == 'failure' &&
           github.event_name == 'push'
+          && needs.build.outcome == 'failure'
         uses: imjohnbo/issue-bot@v3
         with:
           labels: "fix, priority: high"
@@ -259,11 +186,8 @@ jobs:
           body: "It looks like the build is currently failing on the master branch. See failed [action results](https://github.com/patternfly/patternfly-elements/actions/runs/${{ github.run_id }}) for more details."
       - name: Open issue if tests fail
         if: |
-          github.event_name == 'push' &&
-          (
-            needs.test.outcome == 'failure' ||
-            needs.e2e.outcome == 'failure'
-          )
+          github.event_name == 'push'
+          && needs.test.outcome == 'failure'
         uses: imjohnbo/issue-bot@v3
         with:
           labels: "fix, priority: medium"
