chore: Try accessing results

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -296,6 +296,7 @@ jobs:
             .tmp/
             test/vrt-baseline
             test/vrt-snapshots
+            test/vrt-results
           if-no-files-found: error
 
       - name: Stop BrowserStackLocal
@@ -304,16 +305,31 @@ jobs:
         with:
           local-testing: stop
 
-      # Report on the results of the visual regression tests
-      # only if this is a pull request & the tests weren't skipped
-      # This will return pass or fail based on results + labels and can
-      # be used as a required test to ensure passing visual tests when needed
+  # Report on the results of the visual regression tests
+  # only if this is a pull request & the tests weren't skipped
+  # This will return pass or fail based on results + labels and can
+  # be used as a required test to ensure passing visual tests when needed
+  report_e2e:
+    name: Report on the visual regression tests
+    needs: [e2e]
+    if: always()
+    # if: |
+    #   github.event_name == 'pull_request' && (
+    #     needs.e2e.outcome == 'success' ||
+    #     needs.e2e.outcome == 'failure'
+    #   )
+    runs-on: ubuntu-latest
+    steps:
+      - name: Access assets
+        uses: actions/download-artifact@v2
+        id: download-assets
+        with:
+          name: visual-regression-snapshots
+          path: test/vrt-results
+
       # https://github.com/marketplace/actions/test-reporter
       - name: Report on results in PR
         uses: dorny/test-reporter@v1
-        if: |
-          github.event_name == 'pull_request' &&
-          (success() || failure())
         with:
           # Name or regex of artifact containing test results
           artifact: /(.*).json/
@@ -335,19 +351,19 @@ jobs:
           # Personal access token used to interact with Github API
           token: ${{ secrets.GITHUB_TOKEN }}
 
-      # - name: Return success if passed or intentionally skipped
-      #   if: |
-      #     needs.e2e.outcome == 'success' || 
-      #     contains(github.event.pull_request.labels.*.name, 'skip vrt') || 
-      #     contains(github.event.pull_request.labels.*.name, 'skip e2e')
-      #   run: exit 0
+      - name: Return success if passed or intentionally skipped
+        if: |
+          needs.e2e.outcome == 'success' || 
+          contains(github.event.pull_request.labels.*.name, 'skip vrt') || 
+          contains(github.event.pull_request.labels.*.name, 'skip e2e')
+        run: exit 0
         
-      # - name: Return failure if failed and not skipped
-      #   if: |
-      #     needs.e2e.outcome == 'failure' && 
-      #     !contains(github.event.pull_request.labels.*.name, 'skip vrt') && 
-      #     !contains(github.event.pull_request.labels.*.name, 'skip e2e')
-      #   run: exit 1
+      - name: Return failure if failed and not skipped
+        if: |
+          needs.e2e.outcome == 'failure' && 
+          !contains(github.event.pull_request.labels.*.name, 'skip vrt') && 
+          !contains(github.event.pull_request.labels.*.name, 'skip e2e')
+        run: exit 1
         
   # Validate the build to master was successful; open an issue if not
   validate:
